version: '3'
services:
  lotus-pg:
    image: bitnami/postgresql
    ports: 
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres123
      - POSTGRESQL_DATABASE=lotus-pg